spring.application.name=api-engine

# -------------------------
# PRIMARY DB (PostgreSQL) - JPA
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/api_engine
spring.datasource.username=api_user
spring.datasource.password=api123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -------------------------
# ADVANTAGE DB (JDBC ONLY)
# -------------------------N:\AdJobSys\Dictionary
#advantage.datasource.url=jdbc:extendedsystems:advantage://ERPSYSTEM2/Bacon/Adjobsys/Dictionary/JobSys.add
advantage.datasource.url=jdbc:extendedsystems:advantage://AI-2019/BACON/Adjobsys/Dictionary/JobSys.add
advantage.datasource.username=AdsSys
advantage.datasource.password=jts007
advantage.datasource.driver-class-name=com.extendedsystems.jdbc.advantage.ADSDriver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

